// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VMagicMirrorGrpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Baku.VMagicMirror {
  public static partial class VmmGrpc
  {
    static readonly string __ServiceName = "Baku.VMagicMirror.VmmGrpc";

    static readonly grpc::Marshaller<global::Baku.VMagicMirror.GenericCommandRequest> __Marshaller_Baku_VMagicMirror_GenericCommandRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Baku.VMagicMirror.GenericCommandRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Baku.VMagicMirror.GenericCommandResponse> __Marshaller_Baku_VMagicMirror_GenericCommandResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Baku.VMagicMirror.GenericCommandResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Baku.VMagicMirror.GenericQueryRequest> __Marshaller_Baku_VMagicMirror_GenericQueryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Baku.VMagicMirror.GenericQueryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Baku.VMagicMirror.GenericQueryResponse> __Marshaller_Baku_VMagicMirror_GenericQueryResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Baku.VMagicMirror.GenericQueryResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Baku.VMagicMirror.GenericCommandRequest, global::Baku.VMagicMirror.GenericCommandResponse> __Method_CommandGeneric = new grpc::Method<global::Baku.VMagicMirror.GenericCommandRequest, global::Baku.VMagicMirror.GenericCommandResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CommandGeneric",
        __Marshaller_Baku_VMagicMirror_GenericCommandRequest,
        __Marshaller_Baku_VMagicMirror_GenericCommandResponse);

    static readonly grpc::Method<global::Baku.VMagicMirror.GenericQueryRequest, global::Baku.VMagicMirror.GenericQueryResponse> __Method_QueryGeneric = new grpc::Method<global::Baku.VMagicMirror.GenericQueryRequest, global::Baku.VMagicMirror.GenericQueryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "QueryGeneric",
        __Marshaller_Baku_VMagicMirror_GenericQueryRequest,
        __Marshaller_Baku_VMagicMirror_GenericQueryResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Baku.VMagicMirror.VMagicMirrorGrpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of VmmGrpc</summary>
    public abstract partial class VmmGrpcBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Baku.VMagicMirror.GenericCommandResponse> CommandGeneric(global::Baku.VMagicMirror.GenericCommandRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Baku.VMagicMirror.GenericQueryResponse> QueryGeneric(global::Baku.VMagicMirror.GenericQueryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for VmmGrpc</summary>
    public partial class VmmGrpcClient : grpc::ClientBase<VmmGrpcClient>
    {
      /// <summary>Creates a new client for VmmGrpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public VmmGrpcClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for VmmGrpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public VmmGrpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected VmmGrpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected VmmGrpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Baku.VMagicMirror.GenericCommandResponse CommandGeneric(global::Baku.VMagicMirror.GenericCommandRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CommandGeneric(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Baku.VMagicMirror.GenericCommandResponse CommandGeneric(global::Baku.VMagicMirror.GenericCommandRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CommandGeneric, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Baku.VMagicMirror.GenericCommandResponse> CommandGenericAsync(global::Baku.VMagicMirror.GenericCommandRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CommandGenericAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Baku.VMagicMirror.GenericCommandResponse> CommandGenericAsync(global::Baku.VMagicMirror.GenericCommandRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CommandGeneric, null, options, request);
      }
      public virtual global::Baku.VMagicMirror.GenericQueryResponse QueryGeneric(global::Baku.VMagicMirror.GenericQueryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryGeneric(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Baku.VMagicMirror.GenericQueryResponse QueryGeneric(global::Baku.VMagicMirror.GenericQueryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_QueryGeneric, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Baku.VMagicMirror.GenericQueryResponse> QueryGenericAsync(global::Baku.VMagicMirror.GenericQueryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryGenericAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Baku.VMagicMirror.GenericQueryResponse> QueryGenericAsync(global::Baku.VMagicMirror.GenericQueryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_QueryGeneric, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override VmmGrpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new VmmGrpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(VmmGrpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CommandGeneric, serviceImpl.CommandGeneric)
          .AddMethod(__Method_QueryGeneric, serviceImpl.QueryGeneric).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, VmmGrpcBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CommandGeneric, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Baku.VMagicMirror.GenericCommandRequest, global::Baku.VMagicMirror.GenericCommandResponse>(serviceImpl.CommandGeneric));
      serviceBinder.AddMethod(__Method_QueryGeneric, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Baku.VMagicMirror.GenericQueryRequest, global::Baku.VMagicMirror.GenericQueryResponse>(serviceImpl.QueryGeneric));
    }

  }
}
#endregion
